TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += MCT_global_info.db

DB += MCTSLT01_target.db
DB += MCTSLT01_x_gap_status.db
DB += MCTSLT01_x_centre_status.db
DB += MCTSLT01_y_gap_status.db
DB += MCTSLT01_y_centre_status.db
DB += MCTSLT01_overall_status.db

DB += MCTSLT02_target.db
DB += MCTSLT02_x_gap_status.db
DB += MCTSLT02_x_centre_status.db
DB += MCTSLT02_y_gap_status.db
DB += MCTSLT02_y_centre_status.db
DB += MCTSLT02_overall_status.db

DB += MCTSLT03_target.db
DB += MCTSLT03_x_gap_status.db
DB += MCTSLT03_x_centre_status.db
DB += MCTSLT03_y_gap_status.db
DB += MCTSLT03_y_centre_status.db
DB += MCTSLT03_overall_status.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

